image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda env create -f environment.yml
  - source activate opt2mesh

tests :
  stage: test
  script:
    - python setup.py install
    - pip install pytest
    - cd tests && pytest .