name: opt2mesh
channels:
  - conda-forge
dependencies:
  - h5py==2.10.0
  - joblib==0.17.0
  - numpy==1.19.2
  - pandas==1.1.3
  - pyaml==20.4.0
  - pymesh2==0.3
  - pymeshfix==0.14.1
  - scikit-image==0.17.2
  - scipy==1.5.2
  - torch==1.6.0
  - torchvision==0.7.0